name: Python CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORKDIR: "."

jobs:
  build:
    name: Python ${{ matrix.python-version }} - Line length ${{ matrix.line-length }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11"]
        line-length: [120]

    steps:
      - name: Checkout Repo filtro-engine
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.path .venv

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Choose cache Poetry environment
        run: |
          poetry env use "${{ steps.setup-python.outputs.python-path }}"

      - name: Install dependencies with Poetry
        run: |
          poetry install

      - name: Check code with `isort`
        run: |
          poetry run isort **/*.py --profile black --check-only

      - name: Lint with Ruff
        run: |
          poetry run ruff **/*.py --line-length ${{ matrix.line-length }} --show-source -v

      - name: Check formatting with `black`
        run: |
          poetry run black **/*.py --line-length ${{ matrix.line-length }} --check -v

      - name: Check docstrings with `interrogate`
        run: |
          poetry run interrogate **/*.py -vv

      - name: Check static types with `mypy`
        run: |
          poetry run pip install types-requests types-PyYAML

          poetry run mypy **/*.py --strict --ignore-missing-imports --no-warn-unused-ignores
