name: Test CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  WORKDIR: "."

jobs:
  build:
    name: Tests - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.path .venv

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Choose cache Poetry environment
        run: |
          poetry env use "${{ steps.setup-python.outputs.python-path }}"

      - name: Install dependencies with Poetry
        run: |
          poetry install

      - name: Run tests
        run: |
          make test
